CREATE TABLE GAME (
	SAVE			VARCHAR(5)  NOT NULL,
	CURRENT_PLAYER	INTEGER		NOT NULL,
	ROUND			INTEGER		NOT NULL,
	DIFFICULTY		INTEGER		NOT	NULL,
	NUM_PLAYERS		INTEGER 	NOT	NULL,
	PRIMARY KEY(SAVE)) ENGINE=INNODB;

INSERT INTO GAME VALUES('save1', 0, 0, 0, 0);

CREATE TABLE TILES (
	SAVE			VARCHAR(5)	NOT NULL,
	X_POS			INTEGER 	NOT NULL,
	Y_POS			INTEGER 	NOT NULL,
	TYPE 			VARCHAR(25),
	MULE			INTEGER,
	OWNER			INTEGER,
	PRIMARY KEY (SAVE, X_POS, Y_POS)) ENGINE=INNODB;

INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 0, 0);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 1, 0);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 2, 0);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 3, 0);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 4, 0);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 5, 0);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 6, 0);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 7, 0);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 8, 0);

INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 0, 1);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 1, 1);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 2, 1);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 3, 1);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 4, 1);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 5, 1);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 6, 1);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 7, 1);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 8, 1);

INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 0, 2);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 1, 2);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 2, 2);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 3, 2);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 4, 2);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 5, 2);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 6, 2);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 7, 2);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 8, 2);

INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 0, 3);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 1, 3);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 2, 3);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 3, 3);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 4, 3);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 5, 3);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 6, 3);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 7, 3);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 8, 3);

INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 0, 4);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 1, 4);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 2, 4);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 3, 4);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 4, 4);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 5, 4);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 6, 4);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 7, 4);
INSERT INTO TILES (SAVE, X_POS, Y_POS) VALUES('save1', 8, 4);


CREATE TABLE PLAYERS (
	SAVE			VARCHAR(5)  NOT NULL,
	NAME			VARCHAR(25),
	POSITION		INTEGER		NOT NULL,
	RED 			DOUBLE,
	GREEN			DOUBLE,
	BLUE 			DOUBLE,
	RACE 			VARCHAR(25),
	MONEYS			INTEGER,
	ORE 			INTEGER,
	ENERGY 			INTEGER,
	FOOD			INTEGER,
	MULE			INTEGER,
	CRYSTITE 		INTEGER,
	PRIMARY KEY (SAVE, POSITION)) ENGINE=INNODB;

INSERT INTO PLAYERS (SAVE, POSITION) VALUES('save1', 0);
INSERT INTO PLAYERS (SAVE, POSITION) VALUES('save1', 1);
INSERT INTO PLAYERS (SAVE, POSITION) VALUES('save1', 2);
INSERT INTO PLAYERS (SAVE, POSITION) VALUES('save1', 3);

CREATE TABLE STORE (
	SAVE			VARCHAR(5) NOT NULL,
	ORE 			INTEGER,
	ENERGY			INTEGER,
	FOOD			INTEGER,
	CRYSTITE 		INTEGER,
	MULE			INTEGER,
	PRIMARY KEY(SAVE)) ENGINE=INNODB;

INSERT INTO STORE VALUES('save1', 0, 0, 0, 0, 0);


